### ISSUE TITLE
request failed with code 403 Forbidden: {'detail': 'Invalid token'}

### ISSUE THREAD

**Issue by dineshvm87** [netbox-community/pynetbox#375]
We started getting this error from yesterday and I am trying to find out what changed and what is causing this issue.
We are using a netbox_token to do a get call and we have been using that token since last July. 
Please let me know if anyone can help on this.

[ERROR] RequestError: The request failed with code 403 Forbidden: {'detail': 'Invalid token'}
Traceback (most recent call last):
  File "/var/task/step_functions/validate_cidr.py", line 41, in app
    prefix_object = get_prefix(prefix=data["cidr"], netbox_object=netbox_object)
  File "/var/task/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/var/task/retrying.py", line 212, in call
    raise attempt.get()
  File "/var/task/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/var/task/six.py", line 693, in reraise
    raise value
  File "/var/task/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/var/task/common/netbox.py", line 16, in get_prefix
    return netbox_object.ipam.prefixes.get(prefix=prefix)
  File "/var/task/pynetbox/core/endpoint.py", line 138, in get
    filter_lookup = self.filter(**kwargs)
  File "/var/task/pynetbox/core/endpoint.py", line 225, in filter
    ret = [self._response_loader(i) for i in req.get()]
  File "/var/task/pynetbox/core/query.py", line 300, in get
    return req_all()
  File "/var/task/pynetbox/core/query.py", line 279, in req_all
    req = self._make_call(add_params=add_params)
  File "/var/task/pynetbox/core/query.py", line 263, in _make_call
    raise RequestError(req)

**Comment by dineshvm87** [comment]
Found the issue was invalid token but could not find how the token disappeared from netbox.
