### ISSUE TITLE
.create returning 'list' object has no attribute 'items'

### ISSUE THREAD

**Issue by purplecomputer** [netbox-community/pynetbox#379]
Hello,

I am having a strange issue where every time I pull a parent prefix and try to create a child prefix out of it, I am returned with this error

error below

`Traceback (most recent call last):
  File "/Users/<user>PycharmProjects/netboxtest/test.py", line 9, in <module>
    child = gscParent.available_prefixes.create({"prefix_length":27})
  File "/Users/<user>/PycharmProjects/netboxtest/venv/lib/python3.8/site-packages/pynetbox/core/endpoint.py", line 438, in create
    return self.custom_return(
  File "/Users/<user/PycharmProjects/netboxtest/venv/lib/python3.8/site-packages/pynetbox/core/response.py", line 199, in __init__
    self._parse_values(values)
  File "/Users/<user>/PycharmProjects/netboxtest/venv/lib/python3.8/site-packages/pynetbox/core/response.py", line 279, in _parse_values
    for k, v in values.items():
AttributeError: 'list' object has no attribute 'items'`

this is my simple test

`nb = pynetbox.api(NETBOX_URL, token=NETBOX_TKN)

gscParent = nb.ipam.prefixes.get(cf_cloud_fw_prefix='gsc')
child = gscParent.available_prefixes.create({"prefix_length":27})
`

Im running python 3.8 and the latest version of pynetbox. I have tried with older versions of pynetbox with the same result.

My test is similar to whats outlined in the documentation.

https://pynetbox.readthedocs.io/en/latest/IPAM.html

I have tried everything and keep banging my head. Is this a user issue or is there an unknown 'bug'? I cant figured it out.

**Comment by purplecomputer** [comment]
was able to solve the issue after working with my colleagues. Turns out it was my token. I had admin privileges, but when I tried with another token, it worked fine. I'll close this out, but this might be helpful for someone else.
