### ISSUE TITLE
How to install pynetbox with netbox docker ?

### ISSUE THREAD

**Issue by aconte31** [netbox-community/pynetbox#456]
Hello,

I try build an image docker including pynetbox to use it.

Traceback (most recent call last):
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 237, in fetch_command
🧬 loaded config '/etc/netbox/config/configuration.py'
🧬 loaded config '/etc/netbox/config/extra.py'
🧬 loaded config '/etc/netbox/config/logging.py'
🧬 loaded config '/etc/netbox/config/plugins.py'
    app_name = commands[subcommand]
KeyError: 'collectstatic'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/netbox/netbox/netbox/settings.py", line 602, in <module>
    plugin_config = plugin.config
AttributeError: module 'pynetbox' has no attribute 'config'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/netbox/netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 244, in fetch_command
    settings.INSTALLED_APPS
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/netbox/netbox/netbox/settings.py", line 605, in <module>
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Plugin pynetbox does not provide a 'config' variable. This should be defined in the plugin's __init__.py file and point to the PluginConfig subclass.
ERROR: Service 'netbox' failed to build: The command '/bin/sh -c SECRET_KEY="dummy" /opt/netbox/venv/bin/python /opt/netbox/netbox/manage.py collectstatic --no-input' returned a non-zero code: 1

I tried to install it following this doc:
https://github.com/netbox-community/netbox-docker/wiki/Using-Netbox-Plugins

Best regards

Edit:
I edited the configuration.py file and it went smoothly.

**Comment by markkuleinio** [comment]
`pynetbox` is not a NetBox plugin, it is a Python package.

**Comment by aconte31** [comment]
Hello,

I understand, it works perfectly fine. 

Thank you very much,
Best regards.
