### ISSUE TITLE
Cannot update devices anymore with api

### ISSUE THREAD

**Issue by dsc999** [netbox-community/pynetbox#470]
**Netbox version**: v3.2.4
**Pynetbox version**: 6.6.2

I cannot update anymore devices with pynetbox.
I can get the device info:
```
>>> device = nb.dcim.devices.get(q='test-router')
>>> device.site
test
```

But when trying to update, I get the following error message:
```
>>> device.update({'site': 'test2'})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python3.10/site-packages/pynetbox/core/response.py", line 565, in update
    return self.save()
  File "/home/user/.local/lib/python3.10/site-packages/pynetbox/core/response.py", line 529, in save
    updates = self.updates()
  File "/home/user/.local/lib/python3.10/site-packages/pynetbox/core/response.py", line 506, in updates
    diff = self._diff()
  File "/home/user/.local/lib/python3.10/site-packages/pynetbox/core/response.py", line 482, in _diff
    current = Hashabledict({fmt_dict(k, v) for k, v in self.serialize().items()})
  File "/home/user/.local/lib/python3.10/site-packages/pynetbox/core/response.py", line 457, in serialize
    ret[i] = flatten_custom(current_val)
  File "/home/user/.local/lib/python3.10/site-packages/pynetbox/core/response.py", line 61, in flatten_custom
    return {
  File "/home/user/.local/lib/python3.10/site-packages/pynetbox/core/response.py", line 62, in <dictcomp>
    k: v if not isinstance(v, dict) else v["value"] for k, v in custom_dict.items()
KeyError: 'value'
```

The error message is similar to the one on issue [#457](https://github.com/netbox-community/pynetbox/issues/457) but, in my case, all updates on devices are not working anymore.

The weird thing is: if I try to get information on the device, the update seems to work:
```
>>> device.site
'test2'
```

But in the UI, the update didn't work. And if I get the information again with pynetbox, I see no change was applied:
```
>>> device = nb.dcim.devices.get(q='test-router')
>>> device.site
test
```

**Comment by dsc999** [comment]
Closing this 'issue'.
I tried to assign the site with its name, instead of its id.
The issue I am facing is only with objects in custom fields. So it is the same issue as [#457](https://github.com/netbox-community/pynetbox/issues/457).

Closing as duplicate.
