### ISSUE TITLE
AttributeError: object has no attribute "vid"

### ISSUE THREAD

**Issue by jscmenezes** [netbox-community/pynetbox#482]
Trying to create a vlan using pynetbox get the error:

>>> vlan_135 = dict(vid=135, name="outra-vlan", group=1)
>>> netbox.ipam.vlans.create(vlan_135)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/jeronimo/django-projects/sigesd/env_sigesd/lib/python3.8/site-packages/pynetbox/core/response.py", line 324, in __repr__
    return str(self)
  File "/home/jeronimo/django-projects/sigesd/env_sigesd/lib/python3.8/site-packages/pynetbox/models/ipam.py", line 104, in __str__
    return super().__str__() or str(self.vid)
  File "/home/jeronimo/django-projects/sigesd/env_sigesd/lib/python3.8/site-packages/pynetbox/core/response.py", line 298, in __getattr__
    raise AttributeError('object has no attribute "{}"'.format(k))
AttributeError: object has no attribute "vid"

Pynetbox version: 6.6.2
Netbox version: 3.2.4

**Comment by markkuleinio** [comment]
Works here:

```
>>> netbox.ipam.vlan_groups.get(1)
Group1
>>> vlan_135 = dict(vid=135, name="outra-vlan", group=1)
>>> vlan_135
{'vid': 135, 'name': 'outra-vlan', 'group': 1}
>>> netbox.ipam.vlans.create(vlan_135)
outra-vlan
>>> pynetbox.__version__
'6.6.2'
>>> netbox.status()["netbox-version"]
'3.2.5'
>>> import sys; sys.version
'3.7.3 (default, Jan 22 2021, 20:04:44) \n[GCC 8.3.0]'
>>>
```

All kinds of strange errors occur if your NetBox URL is incorrect when using `pynetbox` (for example, http vs. https) or the reverse proxy (Apache/Nginx) in NetBox is incorrectly configured.

**Comment by jscmenezes** [comment]
Yes! That is it!
Netbox URL was pointing to HTTP. Changed to HTTPS and worked!
Thanks!
