### ISSUE TITLE
NetBox API /dcim/interfaces/{id}/trace/ not working in pynetbox

### ISSUE THREAD

**Issue by jwbensley** [netbox-community/pynetbox#494]
NetBox v3.3.0
pynetbox v6.6.2

The screenshot below shows the mapping of cables from a physical interface, through some patch panels, to a circuit:

![Bildschirmfoto vom 2022-08-30 10-43-17](https://user-images.githubusercontent.com/1025875/187392851-10b45c9b-5f4d-49e3-a332-23fe764ac0f1.png)

This can be queried via the NetBox API directly (using cURL) without issue. I want to get the ID of the circuit at the end of this cable trace (which has ID 2):

![Bildschirmfoto vom 2022-08-30 10-45-38](https://user-images.githubusercontent.com/1025875/187392987-3b24e6bb-d732-401f-8446-3f23a45d1fdc.png)

Via pynetbox this doesn't work though:

```python3
$python3
Python 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pynetbox
>>> nb = pynetbox.api('http://localhost:8080',token='0123456789abcdef0123456789abcdef01234567')
>>> nb.dcim.interfaces.get(name="Ethernet2",device="router1-ber1-de").trace()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bensley/Dokumente/gitlab/network-automation/.venv/lib/python3.10/site-packages/pynetbox/models/dcim.py", line 53, in trace
    urlsplit(hop_item_data["url"])
TypeError: list indices must be integers or slices, not str
>>> x = nb.dcim.interfaces.get(name="Ethernet2",device="router1")
>>> x.trace()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bensley/xyz/.venv/lib/python3.10/site-packages/pynetbox/models/dcim.py", line 53, in trace
    urlsplit(hop_item_data["url"])
TypeError: list indices must be integers or slices, not str
>>> x.name
'Ethernet2'
>>> x.id
2
```

**Comment by rml596** [comment]
I am seeing this as well.

**Comment by netixx** [comment]
Same here,

I am using
```
from pynetbox.core.query import Request


def get_iface_trace(nb: pynetbox.api, iface_id: int):

    return Request(
        base="{}/dcim/interfaces/{}/trace/".format(
            nb.base_url,
            iface_id,
        ),
        token=nb.token,
        private_key=nb.private_key,
        http_session=nb.http_session,
    ).get()
```

as a workaround for now.

**Comment by arthanson** [comment]
This should be fixed in #508 closing.
