### ISSUE TITLE
Save of cable tags not working

### ISSUE THREAD

**Issue by powerscooter** [netbox-community/pynetbox#502]
Hey everybody. 
I installed the newest version of netbox. (version: 3.3.5)
Now i have the problem, that i can not save new tags via pynetbox.

I tried this:
`>>> nb_cable.tags = [11]
>>> nb_cable.tags
[11]
>>> nb_cable.save()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/pynetbox/core/response.py", line 529, in save
    updates = self.updates()
  File "/usr/local/lib/python3.8/dist-packages/pynetbox/core/response.py", line 506, in updates
    diff = self._diff()
  File "/usr/local/lib/python3.8/dist-packages/pynetbox/core/response.py", line 482, in _diff
    current = Hashabledict({fmt_dict(k, v) for k, v in self.serialize().items()})
  File "/usr/local/lib/python3.8/dist-packages/pynetbox/core/response.py", line 463, in serialize
    current_val = [
  File "/usr/local/lib/python3.8/dist-packages/pynetbox/core/response.py", line 464, in <listcomp>
    v.id if isinstance(v, Record) else v for v in current_val
  File "/usr/local/lib/python3.8/dist-packages/pynetbox/core/response.py", line 298, in __getattr__
    raise AttributeError('object has no attribute "{}"'.format(k))
AttributeError: object has no attribute "id"`

Do i did something wrong? It was working by this way in netbox-version 3.2.9.

Thanks

**Comment by egreenspan2** [comment]
I think these are related #491

**Comment by arthanson** [comment]
This was fixed via https://github.com/netbox-community/pynetbox/pull/662 closing this issue.
