### ISSUE TITLE
Inconsistent Duplicate IP address found in global table?

### ISSUE THREAD

**Issue by claremont-awilson** [netbox-community/pynetbox#537]
I have the ENFORCE_GLOBAL_UNIQUE: "true" setting enabled on our environment. 

I've found that if I attempt to update an existing IP address it silently fails (i.e. no change) but on others it errors out. Here are 4 updates on 1 example with no error, followed by 1 update that does error:

```
>>> nb.ipam.ip_addresses.update([dict(id=149,address="192.168.50.22/24",assigned_object_type="virtualization.vminterface")])
[]
>>> nb.ipam.ip_addresses.update([dict(id=149,address="192.168.50.22/24",assigned_object_type="virtualization.vminterface")])
[]
>>> nb.ipam.ip_addresses.update([dict(id=149,address="192.168.50.22/24",assigned_object_type="virtualization.vminterface")])
[]
>>> nb.ipam.ip_addresses.update([dict(id=149,address="192.168.50.22/24",assigned_object_type="virtualization.vminterface")])
[]
nb.ipam.ip_addresses.update([dict(id=151,address="192.168.50.10/24",assigned_object_type="virtualization.vminterface")])
  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/usr/local/lib/python3.6/site-packages/pynetbox/core/endpoint.py", line 385, in update
      ).patch(series)
    File "/usr/local/lib/python3.6/site-packages/pynetbox/core/query.py", line 424, in patch
      return self._make_call(verb="patch", data=data)
    File "/usr/local/lib/python3.6/site-packages/pynetbox/core/query.py", line 284, in _make_call
      raise RequestError(req)
  pynetbox.core.query.RequestError: The request failed with code 400 Bad Request: {'address': ['Duplicate IP address found in global table: 192.168.50.10/24']}
```

I'm not entirely sure which behvaviour I expect as I'm performing an update rather than a create i.e. if I'm doing an update, why error that it's a duplicate? It should just over-write I'd have thought. If it's failing silently, is it really responding that the update is a success and because nothing has changed, it outputs nothing?

**Comment by nautics889** [comment]
Can you please specify what version of pynetbox do you use? It isn't the lastest release according to the traceback output.

**Comment by claremont-awilson** [comment]
I was using 7.0.0, just upgraded to 7.0.1 and got the same thing unfortunately.

```
>>> print(pynetbox.__version__)
7.0.1
>>> nb.ipam.ip_addresses.update([dict(id=150,address="192.168.50.20/24",assigned_object_type="virtualization.vminterface")])
[]
>>> nb.ipam.ip_addresses.update([dict(id=151,address="172.21.3.169/24",assigned_object_type="virtualization.vminterface")])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/pynetbox/core/endpoint.py", line 481, in update
    ).patch(series)
  File "/usr/local/lib/python3.6/site-packages/pynetbox/core/query.py", line 385, in patch
    return self._make_call(verb="patch", data=data)
  File "/usr/local/lib/python3.6/site-packages/pynetbox/core/query.py", line 247, in _make_call
    raise RequestError(req)
pynetbox.core.query.RequestError: The request failed with code 400 Bad Request: {'address': ['Duplicate IP address found in global table: 172.21.3.169/24']}
```

**Comment by markkuleinio** [comment]
Please provide a reproducable data for someone to try it: tell what kind of records we need to create before trying your examples and so on.

**Comment by claremont-awilson** [comment]
I am creating a virtual machine, creating virtual machine interface and then creating IP address and associating it with the virtual machine interface and then attempting to update it.

```
>>> vm = nb.virtualization.virtual_machines.create(dict(name="my_test", site=7))
my_test
>>> interface = nb.virtualization.interfaces.create(virtual_machine=vm.id,name="eth1")
>>> nb.ipam.ip_addresses.create(address="10.98.98.98/24",assigned_object_id=interface.id,assigned_object_type="virtualization.vminterface")
10.98.98.98/24
>>> nb.ipam.ip_addresses.update([dict(id=interface.id,address="10.98.98.98/24",assigned_object_type="virtualization.vmin
terface")])
[]
```

If that helps?

**Comment by markkuleinio** [comment]
```
>>> vm = nb.virtualization.virtual_machines.create(dict(name="my_test", site=3))
>>> vm
my_test
>>> interface = nb.virtualization.interfaces.create(virtual_machine=vm.id,name="eth1")
>>> interface
eth1
>>> nb.ipam.ip_addresses.create(address="10.98.98.98/24",assigned_object_id=interface.id,assigned_object_type="virtualization.vminterface")
10.98.98.98/24
>>> nb.ipam.ip_addresses.update([dict(id=interface.id,address="10.98.98.98/24",assigned_object_type="virtualization.vminterface")])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/markku/temp/venv/lib/python3.9/site-packages/pynetbox/core/endpoint.py", line 477, in update
    req = Request(
  File "/home/markku/temp/venv/lib/python3.9/site-packages/pynetbox/core/query.py", line 385, in patch
    return self._make_call(verb="patch", data=data)
  File "/home/markku/temp/venv/lib/python3.9/site-packages/pynetbox/core/query.py", line 247, in _make_call
    raise RequestError(req)
pynetbox.core.query.RequestError: The request failed with code 400 Bad Request: {'address': ['Duplicate IP address found in global table: 10.98.98.98/24']}
>>>

>>> pynetbox.__version__
'7.0.1'
>>> nb.status()["netbox-version"]
'3.4.6'
>>>
```

But, the last statement in your example doesn't make any sense: You are updating an IP address object (`nb.ipam.ip_addresses.update()`) but you are providing the `id` attribute of an interface (`interface.id`).

**Comment by claremont-awilson** [comment]
Thank you, that was the issue.

I got kind of turned around when working on this as I was using _assigned_object_id_ and I was getting errors relating to _id_ being missing, so I just started using the same value for _id_ (and that error went away, so I just kept using it).

```
get_ipam_address = nb.ipam.ip_addresses.get(
    address=primary_ipv4_address + "/24"
)
nb.ipam.ip_addresses.update(
    [
        dict(
            id=get_ipam_address.id,
            address=get_ipam_address.address
            assigned_object_id=interface.id,
            assigned_object_type="virtualization.vminterface",
        )
    ]
)
```

Not getting the duplicate errors anymore, thanks again!
