### ISSUE TITLE
Keep getting Connection Reset

### ISSUE THREAD

**Issue by rostskadat** [netbox-community/pynetbox#594]
### pynetbox version

v7.2.0

### NetBox version

v3.0.12

### Python version

3.10

### Steps to Reproduce

1. Get an API:
```
nb = pynetbox.api(args.api_url, token=args.token)
```

2. Create a VRF:

```
vrf = nb.ipam.vrfs.create(name="name", description="description")
```
3. Then try to obtain a cluster id

```
cluster_id = nb.virtualization.clusters.filter(cluster=cluster).__next__().id
```

This fails with a `ConnectionResetError`:

```
ERROR | ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Traceback (most recent call last):
  File "/home/rostskadat/git/upworks/Freelance-73-Gitlab-CICD/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/home/rostskadat/git/upworks/Freelance-73-Gitlab-CICD/.venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "/project/.venv/lib/python3.10/site-packages/urllib3/connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
```

### Expected Behavior

The error is intermittent. If I add an HTTPAdapter with a retry then it eventually works fine. 

### Observed Behavior

A `ConnectionResetError` was raised

**Comment by markkuleinio** [comment]
I'd suggest moving this issue to a discussion as `pynetbox` does not raise `ConnectionResetError`s, so the user needs some other help with the system.

There is no mention about the runtime environment but the output it not from from a pure `cluster_id = ...` statement.

**Comment by rostskadat** [comment]
Hello @markkuleinio ,

Thanks for your reply. I understand that it might not be an issue with pynetbox proper but I wasn't really sure where to start. I will however move this to a discussion.

Regards
